/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author Andres Muñoz Bravo
 */
public class VistaElegirDados extends javax.swing.JFrame {
    public JButton[] botonesDados;
    /**
     * Creates new form VistaElegirDados
     */
    public VistaElegirDados() {
        
        initComponents();
        /*this.panelTerreno.setLayout(new GridLayout(15,15));
        for (int i=0;i<5;i++){
            for (int j=0;j<3;j++){
                botonesDados [i][j]= new JButton();
                botonesDados [i][j].setIcon(null);
                botonesDados [i][j].setBorderPainted(true);
                this.panelTerreno.add(botones[i][j]); 
            }
        
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btnLanzar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setText("dado1");

        btn2.setText("dado2");

        btn3.setText("dado3");

        btn4.setText("dado4");

        btn5.setText("dado5");

        btn6.setText("dado6");

        btn7.setText("dado7");

        btn8.setText("dado8");

        btn9.setText("dado9");

        btn10.setText("dado10");

        btn11.setText("dado11");

        btn12.setText("dado12");

        btn14.setText("dado14");

        btn15.setText("dado15");

        btn13.setText("dado13");

        btnLanzar.setText("Lanzar!!!");

        btnSalir.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4)
                        .addGap(38, 38, 38)
                        .addComponent(btn5)
                        .addGap(41, 41, 41)
                        .addComponent(btn6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1)
                        .addGap(38, 38, 38)
                        .addComponent(btn2)
                        .addGap(41, 41, 41)
                        .addComponent(btn3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn14))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn11))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn7)
                                    .addGap(38, 38, 38)
                                    .addComponent(btn8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnSalir)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn15)
                            .addComponent(btn12)
                            .addComponent(btn9)
                            .addComponent(btnLanzar))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn10)
                    .addComponent(btn11)
                    .addComponent(btn12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn13)
                    .addComponent(btn14)
                    .addComponent(btn15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLanzar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaElegirDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaElegirDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaElegirDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaElegirDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaElegirDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnLanzar;
    private javax.swing.JButton btnSalir;
    // End of variables declaration//GEN-END:variables
    public JButton getBtn1(){
        return this.btn1;
    }
    public JButton getBtn2(){
        return this.btn2;
    }
    public JButton getBtn3(){
        return this.btn3;
    }public JButton getBtn4(){
        return this.btn4;
    }public JButton getBtn5(){
        return this.btn5;
    }
    public JButton getBtn6(){
        return this.btn6;
    }public JButton getBtn7(){
        return this.btn7;
    }public JButton getBtn8(){
        return this.btn8;
    }
    public JButton getBtn9(){
        return this.btn9;
    }
    public JButton getBtn10(){
        return this.btn10;
    }
    public JButton getBtn11(){
        return this.btn11;
    }
    public JButton getBtn12(){
        return this.btn12;
    }
    public JButton getBtn13(){
        return this.btn13;
    }
    public JButton getBtn14(){
        return this.btn14;
    }
    public JButton getBtn15(){
        return this.btn15;
    }
    
    public void agregarListener(ActionListener al, MouseListener ml){
        this.btn1.addActionListener(al);
        this.btn2.addActionListener(al);
        this.btn3.addActionListener(al);
        this.btn4.addActionListener(al);
        this.btn5.addActionListener(al);
        this.btn6.addActionListener(al);
        this.btn7.addActionListener(al);
        this.btn8.addActionListener(al);
        this.btn9.addActionListener(al);
        this.btn10.addActionListener(al);
        this.btn11.addActionListener(al);
        this.btn12.addActionListener(al);
        this.btn13.addActionListener(al);
        this.btn14.addActionListener(al);
        this.btn15.addActionListener(al);
        this.btn1.addMouseListener(ml);
        this.btn2.addMouseListener(ml);
        this.btn3.addMouseListener(ml);
        this.btn4.addMouseListener(ml);
        this.btn5.addMouseListener(ml);
        this.btn6.addMouseListener(ml);
        this.btn7.addMouseListener(ml);
        this.btn8.addMouseListener(ml);
        this.btn9.addMouseListener(ml);
        this.btn10.addMouseListener(ml);
        this.btn11.addMouseListener(ml);
        this.btn12.addMouseListener(ml);
        this.btn13.addMouseListener(ml);
        this.btn14.addMouseListener(ml);
        this.btn15.addMouseListener(ml);
        
        
        
        
        
        
    }
    
    
    
    
    
}

